version: 2.1

jobs:
  build:
    docker:
      - image: nginx:latest
    steps:
      - checkout
      - run:
          name: cp html
          command: cp html /usr/share/nginx/html
      - run:
          name: Access Web Page
          command: curl http://localhost
