version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.10.0
  aws-ecs: circleci/aws-ecs@1.2.0
workflows:
  build-and-deploy:
    jobs:
      # ビルとテストを実行するジョブ
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'nginx-sample'
          tag: '${CIRCLE_SHA1}'

      - hold:
          requires:
            - aws-ecr/build-and-push-image
          type: approval                       # プルリク承認まで待機

      # ECSへデプロイを実行するジョブ
      - aws-ecs/deploy-service-update:
          requires:
            - hold
          family: 'nginx-sample-Task'          # タスク名
          service-name: 'nginx-sample-Service' # サービス名
          cluster-name: 'nginx-sample-Cluster' # クラスタ名
          container-image-name-updates: 'container=nginx-sample,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx-sample:${CIRCLE_SHA1}'

