version: 2.1

jobs:
  build:
    docker:
      - image: nginx:latest
    step:
      - run:
          name: Docker Build
          command: docker build .
      - run:
          name: Access Web Page
          command: curl http://localhost
